Algoritmo "Sistema de Repetição"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/08/2020
Var
// Seção de Declarações das variáveis 
x :inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Sistema de Repetição")
para x<-1 até 200 faca
escreval()
escreval("Proa4.0" ,x)
fimpara


Fimalgoritmo