Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/08/2020
Var
// Seção de Declarações das variáveis 
i :inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("mutiplos positivos de 7 inferiores a 1000..")
para i de 7 ate <=1000 passo 7 faca
se (i%7=0) entao
escreval(i)
fimse




fimpara
Fimalgoritmo