Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/08/2020
Var
// Seção de Declarações das variáveis 
i, soma: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para i de 85 ate 907 faca
se (i mod 2 = 0) entao
escreval(i)
soma <- soma + i
fimse
fimpara
escreva ("A soma dos números pares entre 85 e 907 é", soma)


Fimalgoritmo