Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
// Seção de Declarações das variáveis 
area,raio, :real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval("qual o raio da area?")
leia(raio)
escreval()

area<-(raio*raio)
escreval("a area é")
escreval("",area)




Fimalgoritmo