Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/08/2020
Var
   // Seção de Declarações das variáveis
   C , F:real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval ("Temperatura em graus Celsius:")
   Leia (C)
   F <- (9 * C + 160)/5
   Escreval ("A temperatura convertida para Fahrenheit é:",F)

Fimalgoritmo