Algoritmo "ex.5"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/08/2020
Var
// Seção de Declarações das variáveis 
numero :inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Digite um número")
  leia(numero)
se numero mod 2 = 0 entao
      escreva("O número" , numero," é par!")
senao
      escreva("O número" , numero, " é ímpar!")
fimse
Fimalgoritmo