Algoritmo "ex.6"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/08/2020
Var
// Seção de Declarações das variáveis
velo,m,vn :real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite a velocidade do veiculo")
leia(velo)
escreval()
vn<- 433.4 /velo
m<- velo/3,6
escreval("o precursor de SP até o rJ vai durar ..",vn,"horas")
escreval("velociadade em m/s..",m)

Fimalgoritmo